/**
 * @file
 * @author Witek902 (witek902@gmail.com)
 * @brief  Declarations of VertexBuffersScene functions
 *
 * This test checks following functionalities:
 * * binding multiple vertex buffers (one containing positions and second containing color)
 * * instancing - binding third buffer containing per-instance data
 * * dynamic vertex buffers
 */

#pragma once

#include "Scene.hpp"

#include "Engine/Common/Math/Vec4f.hpp"


class VertexBuffersScene : public Scene
{
    struct InstanceData
    {
        NFE::Math::Vec3f pos;
        NFE::Math::Vec4fU color;
    };

    // Renderer interfaces generated by VertexBuffersScene

    NFE::Renderer::RenderTargetPtr mWindowRenderTarget;

    NFE::Renderer::ShaderPtr mVertexShader;
    NFE::Renderer::ShaderPtr mPixelShader;

    NFE::Renderer::BufferPtr mPositionsVertexBuffer;
    NFE::Renderer::BufferPtr mColorVertexBuffer;
    NFE::Renderer::BufferPtr mInstanceBuffer;
    NFE::Renderer::BufferPtr mIndexBuffer;
    NFE::Renderer::VertexLayoutPtr mVertexLayout;

    NFE::Renderer::PipelineStatePtr mPipelineState;
    NFE::Renderer::ResourceBindingLayoutPtr mResBindingLayout;


    // for dynamic vertex buffers
    std::vector<InstanceData> mInstancesData;
    std::vector<NFE::Math::Vec2f> mVelocities;
    NFE::Renderer::ResourceAccessMode mVertexBufferMode;

    // Releases only subscene-related resources. Backbuffer, RT and BlendState stay intact.
    void ReleaseSubsceneResources() override;

    // Resource creators for subscenes
    bool LoadShaders(bool useInstancing);
    bool CreateBuffers(bool withInstanceBuffer, NFE::Renderer::ResourceAccessMode vertexBufferMode);

    // Subscenes
    bool CreateSubSceneSimple();
    bool CreateSubSceneInstancing(NFE::Renderer::ResourceAccessMode vertexBufferMode);

public:
    VertexBuffersScene();
    ~VertexBuffersScene();

    bool OnInit(void* winHandle) override;
    void Draw(float dt) override;
    void Release() override;
};
