/**
 * @file
 * @author Witek902 (witek902@gmail.com)
 * @brief  Declarations of DepthStencilScene functions
 */

#pragma once

#include "Scene.hpp"

class DepthStencilScene: public Scene
{
    /// Renderer interfaces generated by the scene
    NFE::Renderer::BackbufferPtr mWindowBackbuffer;
    NFE::Renderer::RenderTargetPtr mWindowRenderTarget;
    NFE::Renderer::TexturePtr mDepthBuffer;

    NFE::Renderer::ShaderPtr mVertexShader;
    NFE::Renderer::ShaderPtr mPixelShader;
    NFE::Renderer::BufferPtr mConstantBuffer;
    NFE::Renderer::BufferPtr mVertexBuffer;
    NFE::Renderer::BufferPtr mIndexBuffer;
    NFE::Renderer::VertexLayoutPtr mVertexLayout;

    NFE::Renderer::PipelineStatePtr mMaskPipelineState;
    NFE::Renderer::PipelineStatePtr mReflectionPipelineState;
    NFE::Renderer::PipelineStatePtr mFloorPipelineState;
    NFE::Renderer::PipelineStatePtr mCubePipelineState;

    NFE::Renderer::ResourceBindingLayoutPtr mResBindingLayout;

    float mAngle;

    void ReleaseSubsceneResources() override;

    bool CreateBasicResources(bool withDepth, bool withStencil);
    bool CreateDepthBuffer(bool withStencil);

    /// Subscenes
    bool CreateSubSceneNoDepthBuffer();
    bool CreateSubSceneDepthBuffer();
    bool CreateSubSceneDepthStencilBuffer();
    // TODO: multisampled depth buffer

public:
    DepthStencilScene();
    ~DepthStencilScene();

    bool OnInit(void* winHandle) override;
    bool OnSwitchSubscene() override;
    void Draw(float dt) override;
    void Release() override;
};
